name: fusion_works
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2 # Dependency Injection
  logging: 1.2.0 # Logger
  intl: 0.18.1 # Localization
  connectivity_plus: ^6.0.3 # Internet connection check
  shared_preferences: ^2.2.3 # Local storage
  json_annotation: ^4.9.0 # Annotations for json generator
  flutter_svg: ^2.0.10+1 # Svg to widget
  retrofit: ^4.1.0 # Network calls
  mobx: ^2.3.3+2 # State manager
  flutter_mobx: ^2.2.1+1 # State manager widgets
  flutter_secure_storage: ^9.2.2 # Local storage for sensitive data
  dio: ^5.5.0+1 # Added to avoid warning
  device_preview: 1.1.0 # Device Preview
  envied: ^0.5.4+1 # Env secrets
  dropdown_button2: ^2.3.9
  flutter_neat_and_clean_calendar: ^0.3.18+40
  bot_toast: ^4.1.3
  infinite_scroll_pagination: 4.0.0
  async: 2.11.0
  timeago: ^3.7.0
  lottie: ^3.1.2
  skeletonizer: ^1.4.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^8.1.2 # Network calls gen
  build_runner: ^2.4.9 # Code generator
  json_serializable: ^6.8.0 # Json serialization gen
  mobx_codegen: ^2.6.1 # Mobx state manager gen
  flutter_gen_runner: ^5.6.0 # Asset code gen
  very_good_analysis: ^5.1.0 # Linter
  envied_generator: ^0.5.4+1 # env generator

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/text_loader.json
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Black.ttf
          weight: 900
        - asset: fonts/Montserrat-BlackItalic.ttf
          weight: 900
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat-BoldItalic.ttf
          weight: 700
        - asset: fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: fonts/Montserrat-ExtraBoldItalic.ttf
          weight: 800
        - asset: fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: fonts/Montserrat-ExtraLightItalic.ttf
          weight: 200
        - asset: fonts/Montserrat-Italic.ttf
          weight: 400
        - asset: fonts/Montserrat-Light.ttf
          weight: 300
        - asset: fonts/Montserrat-LightItalic.ttf
          weight: 300
        - asset: fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat-MediumItalic.ttf
          weight: 500
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/Montserrat-SemiBoldItalic.ttf
          weight: 600
        - asset: fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: fonts/Montserrat-ThinItalic.ttf
          weight: 100

flutter_gen:
  integrations:
    flutter_svg: true

flutter_intl:
  enabled: true
  class_name: Str
