name: fusion_works
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2 # Dependency Injection
  logging: 1.2.0 # Logger
  intl: 0.18.1 # Localization
  connectivity_plus: ^6.0.3 # Internet connection check
  shared_preferences: ^2.2.3 # Local storage
  json_annotation: ^4.9.0 # Annotations for json generator
  flutter_svg: ^2.0.10+1 # Svg to widget
  retrofit: ^4.1.0 # Network calls
  mobx: ^2.3.3+2 # State manager
  flutter_mobx: ^2.2.1+1 # State manager widgets
  flutter_secure_storage: ^9.2.2 # Local storage for sensitive data
  dio: ^5.5.0+1 # Added to avoid warning
  device_preview: 1.1.0 # Device Preview
  envied: ^0.5.4+1 # Env secrets

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^8.1.2 # Network calls gen
  build_runner: ^2.4.9 # Code generator
  json_serializable: ^6.8.0 # Json serialization gen
  mobx_codegen: ^2.6.1 # Mobx state manager gen
  flutter_gen_runner: ^5.6.0 # Asset code gen
  very_good_analysis: ^5.1.0 # Linter
  envied_generator: ^0.5.4+1 # env generator

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

flutter_gen:
  integrations:
    flutter_svg: true

flutter_intl:
  enabled: true
  class_name: Str
