import '../model/response/skill/skill_dm.dart';

final skillsList = [
  SkillDm(
    id: 1,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    stype: 'PRIMARY',
    category: 'Dart',
    level: 'BEGINNER',
    skill: 'Types',
    status: 'APPROVED',
    comment: null,
  ),
  SkillDm(
    id: 2,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    stype: 'PRIMARY',
    category: 'Dart',
    level: 'BEGINNER',
    skill: 'OOP',
    status: 'APPROVED',
    comment: null,
  ),
  SkillDm(
    id: 3,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    stype: 'PRIMARY',
    category: 'Dart',
    level: 'BEGINNER',
    skill: 'Asynchronous Programming',
    status: 'APPROVED',
    comment: null,
  ),
  SkillDm(
    id: 4,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    stype: 'PRIMARY',
    category: 'Dart',
    level: 'BEGINNER',
    skill: 'Functional Programming',
    status: 'APPROVED',
    comment: null,
  ),
  SkillDm(
    id: 5,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    stype: 'PRIMARY',
    category: 'Dart',
    level: 'BEGINNER',
    skill: 'Error Handling',
    status: 'APPROVED',
    comment: null,
  ),
  SkillDm(
    id: 6,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    stype: 'PRIMARY',
    category: 'Flutter',
    level: 'INTERMEDIATE',
    skill: 'State Management',
    status: 'APPROVED',
    comment: null,
  ),
  SkillDm(
    id: 7,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    stype: 'PRIMARY',
    category: 'Flutter',
    level: 'INTERMEDIATE',
    skill: 'Animations',
    status: 'APPROVED',
    comment: null,
  ),
  SkillDm(
    id: 8,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    stype: 'PRIMARY',
    category: 'Flutter',
    level: 'INTERMEDIATE',
    skill: 'Networking',
    status: 'APPROVED',
    comment: null,
  ),
  SkillDm(
    id: 9,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    stype: 'PRIMARY',
    category: 'Flutter',
    level: 'INTERMEDIATE',
    skill: 'Custom Widgets',
    status: 'APPROVED',
    comment: null,
  ),
  SkillDm(
    id: 10,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    stype: 'PRIMARY',
    category: 'Flutter',
    level: 'ADVANCED',
    skill: 'Performance Optimization',
    status: 'APPROVED',
    comment: null,
  ),
];
